# Setup
title:        X-assistant的专栏
tagline:      既然选择了远方，便只顾风雨兼程！
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       X-assistant
  url:        https://github.com/X-assistant

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
